#!/bin/bash
# 审查报告导出
# 生成 Markdown / HTML 格式的审查报告

set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

TARGET_DIR="${1:-.}"
FORMAT="${2:-markdown}"  # markdown, html
OUTPUT="${3:-}"

echo -e "${CYAN}📄 Export Report / 审查报告导出${NC}"
echo "=========================================="
echo ""

cd "$TARGET_DIR"

# 生成报告文件名
REPO_NAME=$(basename "$(git rev-parse --show-toplevel 2>/dev/null || echo 'repo')")
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

if [[ -z "$OUTPUT" ]]; then
    OUTPUT="${REPO_NAME}_review_${TIMESTAMP}.${FORMAT}"
fi

# 获取审查数据
COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
AUTHOR=$(git log -1 --pretty=format:"%an" 2>/dev/null || echo "unknown")
DATE=$(date '+%Y-%m-%d %H:%M:%S')

CHANGED_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null || git diff --name-only 2>/dev/null || true)
FILE_COUNT=$(printf '%s\n' "$CHANGED_FILES" | grep -v '^$' | wc -l | tr -d ' ')

STATS=$(git diff --shortstat HEAD~1..HEAD 2>/dev/null || git diff --shortstat 2>/dev/null || true)

# 生成 Markdown 报告
if [[ "$FORMAT" == "markdown" ]]; then
    cat > "$OUTPUT" << EOF
# 代码审查报告

## 基本信息

| 项目 | 内容 |
|------|------|
| 仓库 | ${REPO_NAME} |
| 分支 | ${BRANCH} |
| 提交 | ${COMMIT_HASH} |
| 作者 | ${AUTHOR} |
| 时间 | ${DATE} |
| 变更文件 | ${FILE_COUNT} 个 |
| 代码统计 | ${STATS} |

## 变更文件

EOF

    printf '%s\n' "$CHANGED_FILES" | while read -r file; do
        [[ -n "$file" ]] && echo "- \`${file}\`" >> "$OUTPUT"
    done

    cat >> "$OUTPUT" << EOF

## 审查检查项

- [ ] 正确性 (Correctness)
- [ ] 安全性 (Security)
- [ ] 性能 (Performance)
- [ ] 可维护性 (Maintainability)
- [ ] 代码风格 (Style)
- [ ] 测试覆盖 (Test Coverage)

## 审查结果

> 请在 Claude Code 中执行 \`/code-review-assistant\` 获取详细审查结果

---
*Generated by Code Review Assistant*
EOF

    echo -e "${GREEN}✅ Markdown 报告已生成: ${OUTPUT}${NC}"

# 生成 HTML 报告
elif [[ "$FORMAT" == "html" ]]; then
    cat > "$OUTPUT" << EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>代码审查报告 - ${REPO_NAME}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 40px auto; padding: 20px; color: #333; }
        h1 { color: #1a1a1a; border-bottom: 2px solid #e0e0e0; padding-bottom: 10px; }
        h2 { color: #333; margin-top: 30px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e0e0e0; }
        th { background: #f5f5f5; font-weight: 600; }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; }
        .badge-info { background: #e3f2fd; color: #1976d2; }
        .badge-warning { background: #fff3e0; color: #f57c00; }
        .badge-danger { background: #ffebee; color: #c62828; }
        .file-list { background: #f8f9fa; padding: 15px; border-radius: 8px; }
        .file-list li { padding: 4px 0; font-family: monospace; }
        .checklist { list-style: none; padding: 0; }
        .checklist li { padding: 8px 0; }
        .checklist li::before { content: "☐ "; margin-right: 8px; }
        footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; color: #999; font-size: 12px; }
    </style>
</head>
<body>
    <h1>📝 代码审查报告</h1>

    <h2>基本信息</h2>
    <table>
        <tr><th>项目</th><th>内容</th></tr>
        <tr><td>仓库</td><td><span class="badge badge-info">${REPO_NAME}</span></td></tr>
        <tr><td>分支</td><td>${BRANCH}</td></tr>
        <tr><td>提交</td><td><code>${COMMIT_HASH}</code></td></tr>
        <tr><td>作者</td><td>${AUTHOR}</td></tr>
        <tr><td>时间</td><td>${DATE}</td></tr>
        <tr><td>变更文件</td><td><strong>${FILE_COUNT} 个</strong></td></tr>
    </table>

    <h2>变更文件</h2>
    <ul class="file-list">
EOF

    printf '%s\n' "$CHANGED_FILES" | while read -r file; do
        [[ -n "$file" ]] && echo "        <li>${file}</li>" >> "$OUTPUT"
    done

    cat >> "$OUTPUT" << EOF
    </ul>

    <h2>审查检查项</h2>
    <ul class="checklist">
        <li>正确性 (Correctness)</li>
        <li>安全性 (Security)</li>
        <li>性能 (Performance)</li>
        <li>可维护性 (Maintainability)</li>
        <li>代码风格 (Style)</li>
        <li>测试覆盖 (Test Coverage)</li>
    </ul>

    <h2>审查结果</h2>
    <p>请在 Claude Code 中执行 <code>/code-review-assistant</code> 获取详细审查结果</p>

    <footer>
        Generated by Code Review Assistant | ${DATE}
    </footer>
</body>
</html>
EOF

    echo -e "${GREEN}✅ HTML 报告已生成: ${OUTPUT}${NC}"
else
    echo -e "${RED}不支持的格式: ${FORMAT}${NC}"
    echo "支持的格式: markdown, html"
    exit 1
fi

echo ""
echo -e "${YELLOW}报告位置:${NC}"
echo "  $(pwd)/${OUTPUT}"
